### ISSUE TITLE
How to get a transaction receipt from runBlock()?

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-vm#1]
Hey,

I can't figure out how to get a receipt of transaction in the block that is executed by `runBlock()`. `block.transactionReceipt` from docs is undefined and `block.header.receiptTrie` is an empty trie. Here's the full code of my test https://github.com/asinyagin/ethereumjs-test/blob/receipt-test/app.js.

I use this fix to turn off block validation https://github.com/ethereum/ethereumjs-blockchain/pull/2

**Comment by wanderer** [comment]
@asinyagin; `runBlock` now returns to the callback `err, results`. And `results` contains {receipts: Array; txResults: Array} 

example
```
vm.runBlock(function(err, results){
   results.receipts.forEach(function(receipt){
     //do something with `receipt`
   })
})  
```
