### ISSUE TITLE
Contract is not created

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-vm#11]
Hey,

I've found another problem: ethereumjs doesn't create a contract. I think the problem is in contract's code, because the same source code with different contract's code works well.

Here's an example: https://github.com/asinyagin/ethereumjs-test/blob/master/app.js

It shows 2 account at the end, but there should be 3 accounts.

**Comment by wanderer** [comment]
@asinyagin asinyagin taking a look at this now!

**Comment by asinyagin** [comment]
i have the contracts code, so i can post it if you need.

**Comment by wanderer** [comment]
@asinyagin to code errors becuase there is an invalid jump. Do you have the src code?

**Comment by asinyagin** [comment]
yep, it's here https://gist.github.com/asinyagin/da5bdfc68a5d950047be
