### ISSUE TITLE
Created account has no code

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-vm#12]
Hey,

I want to create a new contract without running a transaction, i have the following code for it:
```javascript
function runCode(cb) {
  var account = new Account();
  
  vm.runCode({
    code: account2.code,
    data: account2.code,
    account: account,
    gasLimit: 3141592,
    address: account2.address,
    caller: account1.address
  }, function(err, result) {
    if (err) return cb(err);
    account.setCode(vm.trie, result.return, function(err) {
      if (err) cb(err);
      else vm.trie.put(account2.address, account.serialize(), cb);
    });
  });
}
```

The account has code right after saving, but after next transaction it looses its code. Looks like that happens only if the account has a constructor with storage changing. Here's the full example https://github.com/asinyagin/ethereumjs-test/blob/runCode/app.js . If you comment out the line https://github.com/asinyagin/ethereumjs-test/blob/runCode/app.js#L43 , you'll see that account had code before `runTx()`.

Am I doing something wrong?

**Comment by asinyagin** [comment]
It works well with https://github.com/ethereum/ethereumjs-vm/commit/192c04ff4b5b569a02593891611374774cbc848d, but not with the latest master.

**Comment by wanderer** [comment]
@asinyagin ok it should be working on master now

**Comment by asinyagin** [comment]
@wanderer thanks! it works good now.
