### ISSUE TITLE
Expose constructors

### ISSUE THREAD

**Issue by d11e9** [ethereum/ethereumjs-vm#14]
The newest version of ethereumjs-vm seems to have changes the api such that `Account`, `Trie`, `Transaction` etc are not publicly accessable meaning that users of the browserified version in `./dist` need to re-require those libs to interact with the vm.

Could these be re-exposed?

**Comment by wanderer** [comment]
ok so i exposed them on the `ethVM.deps` object if you are in the browser. I didn't do `Transaction` since the vm never directly requires it.
