### ISSUE TITLE
Is it possible to set the gasLimit of the VM without having to run blocks to increase?

### ISSUE THREAD

**Issue by d11e9** [ethereum/ethereumjs-vm#15]
ie using genesis state etc? looks like it just loads allocations (address => balance) etc

**Comment by wanderer** [comment]
The gas Limit is checked here. https://github.com/ethereum/ethereumjs-vm/blob/master/lib/runTx.js#L30-L34 

It just checks the gasLimit of the current block. If you don't pass in a block a default on is created for you here https://github.com/ethereum/ethereumjs-vm/blob/master/lib/runTx.js#L25-L28

**Comment by kumavis** [comment]
we should increase that default gasLimit to full `f`'s. if you dont care about the block you likely just want your tx to go through unhampered.

**Comment by wanderer** [comment]
@d11e9 does the above answer your question?

**Comment by d11e9** [comment]
@wanderer it did thanks, what @kumavis suggests sounds good though.
