### ISSUE TITLE
Account looses its code

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-vm#16]
Hey,

I have another problem with `runCode()`. Account created with `runCode()` looses his code after calling from another contract. Here's the example https://github.com/asinyagin/ethereumjs-test/tree/runCode. it prints:
```
cd2a3d9f938e13cd947ec05abc7fe734df8dd826: 
0000000000000000000000000000000000000000: 
084f6a99003dae6d3906664fdbf43dd09930d0e3: 
77045e71a7a2c50903d88e564cd72fab11e82051: 60606040526008565b00
```
But account 084f...d0e3 should have code. If you comment out line https://github.com/asinyagin/ethereumjs-test/blob/runCode/app.js#L43 , the account will have its code.

**Comment by kumavis** [comment]
hmm strange... try checkpointing before `runCode`
should be `vm.trie.checkpoint()` or so

**Comment by asinyagin** [comment]
@kumavis i've just tried checkpoint in several places around runCode and setting account's code and it haven't helped.

**Comment by wanderer** [comment]
its a cache issue. The cache seem fragile.

**Comment by wanderer** [comment]
so when you do run code account  `084f6a99003dae6d3906664fdbf43dd09930d0e3` get loaded into the cache. Then when `runTx` runs it just uses what in the cache instead of pulling from the trie. when `runTx` it ends it flushs the cache overwriting `084f6a99003dae6d3906664fdbf43dd09930d0e3`

**Comment by wanderer** [comment]
@asinyagin ok lastest on master should work for you now. I added a `clear` method to cache that gets called only when `populateCache` is not `false`. The VM internally sets it to false when using the run functions.

**Comment by asinyagin** [comment]
@wanderer thanks! it works now.
