### ISSUE TITLE
steams, hooks or events?

### ISSUE THREAD

**Issue by wanderer** [ethereum/ethereumjs-vm#4]
What is the best way to get interesting info out of the VM? First of all what do we want to get? Off the top of my head
*  Per step info for the VM
*  The results for each TX. was the tx successful? did it create a new contract? ect...
*  The results for each Block. was the block successful? what are the Receipts? what are the results from the tx's in the block

The options I can think of are events, hooks and steams.

### events
events would be something like `on("Step" | "tx" | "block" )`

**pros**  
 * are nice because multiple parties can subscribe to them. 

**cons**
* you can't pause the vm. 
* its hard to make events work across the network

### hooks
Hooks are `vm.onTx = function(data, done){}`, `vm.onBlock` and `vm.onStep`

**Pros**
* very minimalist
* can pause the VM

**Cons**
* only can be defined once!

### streams
Streams look like `vm.createTraceStream()`, `vm.createTxStream`, `vm.createBlockStream`

NOTE currently createTraceStream is built on top of the `runStep` hook. If i continued to build out stream I would probably implement them on hooks.

**Pros**
* should work nicely with networks.
* standard format

**Cons**
* can't pause the VM. 

## Currently
we have
`onTx`, `AfterTx` , `onStep`, and `createTraceStream`.

**Comment by wanderer** [comment]
related issues 
https://github.com/ethereum/ethereumjs-vm/issues/1
https://github.com/ethereum/ethereumjs-lib/issues/118

**Comment by wanderer** [comment]
@asinyagin @romanman @kumavis any opinions or suggests?

**Comment by wanderer** [comment]
also note: the only good reason for pausing the VM, i can think of, is for building debugging utils. For example you could pause the VM and then edit the stack or the memory.

**Comment by kumavis** [comment]
absolutely events over hooks -- and you can still handout callbacks for pausing over events, you'll just need use an ee that lets you track the number of listeners. or maybe do a custom ee implementation to handle some behavior as you want (should listeners be parallel or series?) my vote is parallel.

streams are interesting but not sure what the use case is yet.

also pausing the vm is useful! i like this.

**Comment by wanderer** [comment]
@kumavis  i use streams to generate vm traces. What do you mean by ee?

**Comment by kumavis** [comment]
ee = even emitter

**Comment by kumavis** [comment]
you use streams to _deliver_ the vm traces, no?
I suppose you could argue that a stream is more well-ordered than an ee

**Comment by wanderer** [comment]
yeah i really like dealing will with steam. I often write the trace to file, streams make this a snap.

**Comment by wanderer** [comment]
ok definaintly leaning towards Events and build streams on top of them

**Comment by d11e9** [comment]
:+1: for Events.

@wanderer Just for the record are these vm specifc events or events emitted by contracts?

I've been trying to work out how to watch for events fired by a contract running in the vm, havn't yet found a solution.

**Comment by wanderer** [comment]
@d11e9 yeah im going to go with events and will add a pause and resume method to the VM that way we can build streams on top of events and use the pause method when back pressure builds up.

**Comment by kumavis** [comment]
@wanderer nice

**Comment by wanderer** [comment]
ok events are added via [async-eventemitter](https://github.com/ahultgren/async-eventemitter). The current events we have are
* beforeTx - which will give you the Tx about to be run
* afterTx - which will give you the results of the Tx after it has been runned
* step - which emits an event on every step of the VM

**Comment by wanderer** [comment]
@romanj @asinyagin i think this also solve this really old issue https://github.com/ethereum/ethereumjs-lib/issues/118

**Comment by asinyagin** [comment]
@wanderer yeah, the feature with returned values for `runBlock()` has been added some time ago.

And thanks for the events, looking forward to test it.

**Comment by kumavis** [comment]
+1
